# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _RodCosserat4
else:
    import _RodCosserat4

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class RodCosserat4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, dim_np, dim_bf0, theta_n, overall_rot, a_bar, b_bar):
        _RodCosserat4.RodCosserat4_swiginit(self, _RodCosserat4.new_RodCosserat4(dim_np, dim_bf0, theta_n, overall_rot, a_bar, b_bar))
    overall_rot = property(_RodCosserat4.RodCosserat4_overall_rot_get, _RodCosserat4.RodCosserat4_overall_rot_set)
    d_vec = property(_RodCosserat4.RodCosserat4_d_vec_get, _RodCosserat4.RodCosserat4_d_vec_set)
    nv = property(_RodCosserat4.RodCosserat4_nv_get, _RodCosserat4.RodCosserat4_nv_set)
    bigL_bar = property(_RodCosserat4.RodCosserat4_bigL_bar_get, _RodCosserat4.RodCosserat4_bigL_bar_set)
    bf0_bar = property(_RodCosserat4.RodCosserat4_bf0_bar_get, _RodCosserat4.RodCosserat4_bf0_bar_set)
    alpha_bar = property(_RodCosserat4.RodCosserat4_alpha_bar_get, _RodCosserat4.RodCosserat4_alpha_bar_set)
    beta_bar = property(_RodCosserat4.RodCosserat4_beta_bar_get, _RodCosserat4.RodCosserat4_beta_bar_set)
    j_rot = property(_RodCosserat4.RodCosserat4_j_rot_get, _RodCosserat4.RodCosserat4_j_rot_set)
    p_thetan = property(_RodCosserat4.RodCosserat4_p_thetan_get, _RodCosserat4.RodCosserat4_p_thetan_set)
    bf0mat = property(_RodCosserat4.RodCosserat4_bf0mat_get, _RodCosserat4.RodCosserat4_bf0mat_set)
    qe_o2m_loc = property(_RodCosserat4.RodCosserat4_qe_o2m_loc_get, _RodCosserat4.RodCosserat4_qe_o2m_loc_set)
    qe_m2o_loc = property(_RodCosserat4.RodCosserat4_qe_m2o_loc_get, _RodCosserat4.RodCosserat4_qe_m2o_loc_set)
    excl_joints = property(_RodCosserat4.RodCosserat4_excl_joints_get, _RodCosserat4.RodCosserat4_excl_joints_set)
    nintgsteps = property(_RodCosserat4.RodCosserat4_nintgsteps_get, _RodCosserat4.RodCosserat4_nintgsteps_set)
    step_const = property(_RodCosserat4.RodCosserat4_step_const_get, _RodCosserat4.RodCosserat4_step_const_set)
    step_gain = property(_RodCosserat4.RodCosserat4_step_gain_get, _RodCosserat4.RodCosserat4_step_gain_set)

    def updateVars(self, dim_np, dim_bf0, dim_bfe):
        return _RodCosserat4.RodCosserat4_updateVars(self, dim_np, dim_bf0, dim_bfe)

    def calculateCenterlineF2(self, dim_nf):
        return _RodCosserat4.RodCosserat4_calculateCenterlineF2(self, dim_nf)

    def calculateCenterlineTorq(self, dim_nt, dim_nq, excl_jnts):
        return _RodCosserat4.RodCosserat4_calculateCenterlineTorq(self, dim_nt, dim_nq, excl_jnts)

    def calculateF2LocalTorq(self):
        return _RodCosserat4.RodCosserat4_calculateF2LocalTorq(self)

    def updateThetasFullDyn(self, dim_nq):
        return _RodCosserat4.RodCosserat4_updateThetasFullDyn(self, dim_nq)

    def resetTheta(self, theta_n, overall_rot):
        return _RodCosserat4.RodCosserat4_resetTheta(self, theta_n, overall_rot)

    def changeAlphaBeta(self, a_bar, b_bar):
        return _RodCosserat4.RodCosserat4_changeAlphaBeta(self, a_bar, b_bar)

    def initQe_o2m_loc(self, dim_qo2m):
        return _RodCosserat4.RodCosserat4_initQe_o2m_loc(self, dim_qo2m)

    def initO2MLocAll(self, dim_nq):
        return _RodCosserat4.RodCosserat4_initO2MLocAll(self, dim_nq)

    def calculateOf2Mf(self, dim_mato, dim_matres):
        return _RodCosserat4.RodCosserat4_calculateOf2Mf(self, dim_mato, dim_matres)

    def calculateOf2MfAtEdge(self, edge_idx, dim_mato, dim_matres):
        return _RodCosserat4.RodCosserat4_calculateOf2MfAtEdge(self, edge_idx, dim_mato, dim_matres)

    def angBtwn3(self, dim_v1, dim_v2, dim_va):
        return _RodCosserat4.RodCosserat4_angBtwn3(self, dim_v1, dim_v2, dim_va)

    def calculateEnergy(self):
        return _RodCosserat4.RodCosserat4_calculateEnergy(self)
    __swig_destroy__ = _RodCosserat4.delete_RodCosserat4

# Register RodCosserat4 in _RodCosserat4:
_RodCosserat4.RodCosserat4_swigregister(RodCosserat4)



