# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _RodCosserat
else:
    import _RodCosserat

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class RodCosserat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, n_nodes, segment_length, k_bend, k_twist):
        _RodCosserat.RodCosserat_swiginit(self, _RodCosserat.new_RodCosserat(n_nodes, segment_length, k_bend, k_twist))
    __swig_destroy__ = _RodCosserat.delete_RodCosserat

    def setMaterial(self, k_bend, k_twist):
        return _RodCosserat.RodCosserat_setMaterial(self, k_bend, k_twist)

    def setNumIterations(self, num_iters):
        return _RodCosserat.RodCosserat_setNumIterations(self, num_iters)

    def setTorqueGain(self, k_torque):
        return _RodCosserat.RodCosserat_setTorqueGain(self, k_torque)

    def reinitRest(self, dim_x, dim_q):
        return _RodCosserat.RodCosserat_reinitRest(self, dim_x, dim_q)

    def computeWrenches(self, dim_x, dim_q, dt, dim_t):
        return _RodCosserat.RodCosserat_computeWrenches(self, dim_x, dim_q, dt, dim_t)

# Register RodCosserat in _RodCosserat:
_RodCosserat.RodCosserat_swigregister(RodCosserat)

